spring:
  application:
    name: payment-service
  config:
    import:
      - "vault://"
      - "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}"
  cloud:
    vault:
      token: keyword
      scheme: http
      authentication: token
      host: 127.0.0.1
      port: 8200
      kv:
        enabled: true
        backend: taxi-restapi
        default-context: dev
        profile-separator: /
  liquibase:
    enabled: true

---
spring:
  config:
    activate:
      on-profile: docker
    import:
      - "vault://"
      - "configserver:http://config-server:8888"
  cloud:
    vault:
      host: vault
      port: 8200
