server.port: ${SERVER_PORT}

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/thisdudkin/taxi-restapi-config.git
          default-label: main
