server.port: 8082

spring:
  application:
    name: drivers-service

  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: driver-service-consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
    producer:
      acks: all
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      missing-topics-fatal: false
      concurrency: 3

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/taxi-realm/protocol/openid-connect/certs

  elasticsearch:
    uris: http://elasticsearch:9200

  liquibase:
    enabled: true
  messages:
    basename: messages

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
    tags:
      application: driver-service

logging:
  config: classpath:logback-docker.xml
  level:
    liquibase: INFO
    org:
      springframework: INFO

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
