server.port: 8082

spring:
  application:
    name: drivers-service

  boot:
    admin:
      client:
        enabled: true
        instance:
          name: driver-service
        url: http://localhost:8086

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: driver-service-consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
    producer:
      acks: all
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      missing-topics-fatal: false
      concurrency: 3

  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/drivers_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASS:root}

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/realms/taxi-realm/protocol/openid-connect/certs

  liquibase:
    enabled: true
  messages:
    basename: messages

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: '*'
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
    tags:
      application: driver-service

logging:
  level:
    liquibase: INFO
    org:
      springframework: INFO

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
