apiVersion: apps/v1
kind: Deployment
metadata:
  name: passenger-service
  namespace: taxi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: passenger-service
  template:
    metadata:
      labels:
        app: passenger-service
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - business-services
      containers:
        - name: passenger-service
          image: rainaddan/taxi-restapi-passenger-service
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: taxi-app-config
            - secretRef:
                name: taxi-app-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: passenger-service
  namespace: taxi-app
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: passenger-service
