{
 "title": "Taxi REST API",
 "description": "Taxi REST API",
 "tags": [ "taxi-restapi" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({application=\"$application\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", status!~\"5..\"}[1m]))/sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", status!~\"5..\"}[1m]))",
     "legendFormat": "HTTP - AVG"
    },
    {
     "expr": "max(http_server_requests_seconds_max{application=\"$application\", instance=\"$instance\", status!~\"5..\"})",
     "legendFormat": "HTTP - MAX"
    }
   ]
  },
  {
   "title": "Passengers Updated",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(passengers_updated_count_total{instance=\"passenger-service:8081\"})",
     "legendFormat": "Passengers Updated"
    }
   ]
  },
  {
   "title": "Passengers Created",
   "type": "stat",
   "description": "Passengers Created Metric",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(passengers_created_count_total{instance=\"passenger-service:8081\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Drivers Updated",
   "type": "stat",
   "description": "Drivers Updated Metric",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(drivers_updated_count_total{instance=\"driver-service:8082\"})",
     "legendFormat": "Drivers Updated"
    }
   ]
  },
  {
   "title": "Drivers Created",
   "type": "stat",
   "description": "Drivers Created Metric",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(drivers_created_count_total{instance=\"driver-service:8082\"})",
     "legendFormat": "Drivers Created"
    }
   ]
  },
  {
   "title": "Business Metrics Histogram",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(drivers_created_count_total)",
     "legendFormat": "driver create"
    },
    {
     "expr": "sum(passengers_created_count_total)",
     "legendFormat": "passenger create"
    },
    {
     "expr": "sum(passengers_updated_count_total)",
     "legendFormat": "passenger update"
    },
    {
     "expr": "sum(drivers_updated_count_total)",
     "legendFormat": "driver update"
    }
   ]
  }
 ]
}