server.port: 8761

spring:
  application:
    name: discovery-server

  boot:
    admin:
      client:
        enabled: true
        instance:
          name: discovery-server
        url: http://admin-server:8086

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

# Avoid some debugging logs at startup
logging:
  config: classpath:logback-docker.xml
  level:
    org:
      springframework:
        boot: INFO
        web: INFO
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
