# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: api-gateway
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['api-gateway:3030']

  - job_name: authentication-server
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['authentication-server:8087']

  - job_name: passenger-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['passenger-service:8081']

  - job_name: driver-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['driver-service:8082']

  - job_name: rides-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['rides-service:8083']

  - job_name: notification-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['notification-service:8084']

  - job_name: postgres
    static_configs:
      - targets: ['postgres-exporter:9187']
