apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: taxi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - main-services
      containers:
        - name: api-gateway
          image: rainaddan/taxi-restapi-api-gateway
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          ports:
            - containerPort: 3030
          envFrom:
            - configMapRef:
                name: taxi-app-config

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: taxi-app
spec:
  type: LoadBalancer
  ports:
    - port: 3030
      targetPort: 3030
  selector:
    app: api-gateway
