server.port: 8083

spring:
  application:
    name: rides-service

  boot:
    admin:
      client:
        enabled: true
        instance:
          name: rides-service
        url: http://admin-server:8086

  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: ride-service-consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
    producer:
      acks: all
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      missing-topics-fatal: false
      concurrency: 3

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/taxi-realm/protocol/openid-connect/certs

  liquibase:
    enabled: true
  messages:
    basename: messages

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  config: classpath:logback-docker.xml
  level:
    liquibase: INFO
    org:
      springframework: INFO

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://tracing-server:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: '*'
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
    tags:
      application: rides-service
